project_name: search
release:
  github:
    owner: BajomoDavid
    name: kubectl-search
builds:
  - id: search
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/search/main.go
    ldflags: -s -w
      -X github.com/BajomoDavid/kubectl-search/pkg/version.version=
archives:
  - id: search
    builds:
    - search
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip
