apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: search
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/BajomoDavid/kubectl-search-plugin/releases/download/v0.1.0/search_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./search"
      to: "."
    - from: LICENSE
      to: "."
    bin: "search"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/BajomoDavid/kubectl-search-plugin/releases/download/v0.1.0/search_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./search"
      to: "."
    - from: LICENSE
      to: "."
    bin: "search"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/BajomoDavid/kubectl-search-plugin/releases/download/v0.1.0/search_windows_amd64.zip
    sha256: ""
    files:
    - from: "/search.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "search.exe"
  shortDescription: A new plugin
  homepage: https://github.com/BajomoDavid/kubectl-search-plugin
  caveats: |
    Usage:
      $ kubectl search

    For additional options:
      $ kubectl search --help
      or https://github.com/BajomoDavid/kubectl-search-plugin/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
